services:
  nginx:
    image: nginx:latest
    container_name: actuator-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - actuator-network
    restart: unless-stopped

  frontend:
    build:
      context: ./actuator-front
    image: actuator-front:latest
    container_name: actuator-front
    expose:
      - "5005"
    depends_on:
      - backend
    networks:
      - actuator-network
    restart: unless-stopped

  backend:
    build:
      context: ./actuator-back
    image: actuator-back:latest
    container_name: actuator-back
    expose:
      - "4004"
    depends_on:
      - actuator-db
    environment:
      DB_HOST: actuator-db
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: 1209
      DB_NAME: actuator_game
      APP_EMAIL: whwlsgh0523@gmail.com
      APP_PASS: invb xoqc sqtx qeyw
      ANALYTICS_PASSWORD: admin123
    networks:
      - actuator-network
    restart: unless-stopped

  actuator-db:
    image: postgres:16.10
    container_name: actuator-db
    expose:
      - "5433"
    command: ["postgres", "-c", "port=5433"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1209
      POSTGRES_DB: actuator_game
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./actuator-back/sql/schema.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - actuator-network
    restart: unless-stopped

networks:
  actuator-network:
    driver: bridge

volumes:
  db-data:
    driver: local
