version: '3.8'

services:
  frontend:
    build:
      context: ./actuator-front
    image: actuator-front:latest
    container_name: actuator-front
    ports:
      - "5005:5005"
    networks:
      - actuator-network

  backend:
    build:
      context: ./actuator-back
    image: actuator-back:latest
    container_name: actuator-back
    ports:
      - "4004:4004"
    environment:
      DB_HOST: actuator-db
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: 1209
      DB_NAME: actuator_game
      APP_EMAIL: whwlsgh0523@gmail.com
      APP_PASS: invb xoqc sqtx qeyw
      ANALYTICS_PASSWORD: admin123
    networks:
      - actuator-network

  actuator-db:
    image: postgres:16.10
    container_name: actuator-db
    ports:
      - "5433:5433"
    command: ["postgres", "-c", "port=5433"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1209
      POSTGRES_DB: actuator_game
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./actuator-back/sql/schema.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - actuator-network

networks:
  actuator-network:
    driver: bridge

volumes:
  db-data:
    driver: local
